version: "3.8"

services:
  frontend:
    image: ${FRONT_IMAGE}
    container_name: slotfinder-stg-frontend
    restart: unless-stopped
    networks:
      - zide-traefik-n
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=zide-traefik-n"
      - "traefik.http.services.slotfinder-stg-frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.slotfinder-stg-frontend.rule=Host(`${DOMAIN}`) && !PathPrefix(`/api`)"
      - "traefik.http.routers.slotfinder-stg-frontend.entrypoints=websecure"
      - "traefik.http.routers.slotfinder-stg-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.slotfinder-stg-frontend.service=slotfinder-stg-frontend"
      - "traefik.http.routers.slotfinder-stg-frontend-http.rule=Host(`${DOMAIN}`) && !PathPrefix(`/api`)"
      - "traefik.http.routers.slotfinder-stg-frontend-http.entrypoints=web"
      - "traefik.http.routers.slotfinder-stg-frontend-http.service=slotfinder-stg-frontend"

  backend:
    image: ${BACK_IMAGE}
    container_name: slotfinder-stg-backend
    restart: unless-stopped
    networks:
      - zide-traefik-n
    environment:
      - PORT=3000
      - HOST=0.0.0.0
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=zide-traefik-n"
      - "traefik.http.services.slotfinder-stg-backend.loadbalancer.server.port=3000"
      - "traefik.http.routers.slotfinder-stg-backend.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.slotfinder-stg-backend.entrypoints=websecure"
      - "traefik.http.routers.slotfinder-stg-backend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.slotfinder-stg-backend.service=slotfinder-stg-backend"
      - "traefik.http.routers.slotfinder-stg-backend.middlewares=slotfinder-stg-backend-stripprefix"
      - "traefik.http.middlewares.slotfinder-stg-backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.slotfinder-stg-backend-http.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.slotfinder-stg-backend-http.entrypoints=web"
      - "traefik.http.routers.slotfinder-stg-backend-http.service=slotfinder-stg-backend"
      - "traefik.http.routers.slotfinder-stg-backend-http.middlewares=slotfinder-stg-backend-stripprefix"

networks:
  zide-traefik-n:
    external: true
